# Generated by Django 3.2 on 2021-12-24 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=60, verbose_name='Titre')),
                ('overwiew', models.CharField(max_length=20, verbose_name='Bref appercu du post')),
                ('key_words', models.CharField(blank='True', max_length=20, null=True, verbose_name='Mots clés...  Facultatif')),
                ('content', models.TextField(verbose_name='Contenu du post')),
                ('post_image', models.ImageField(upload_to='media', verbose_name='Associer une image')),
                ('post_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypost.post')),
                ('view_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('comment_body', models.TextField(verbose_name='Votre commentaire')),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Commenter par')),
                ('for_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mypost.post')),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ['-created'],
            },
        ),
    ]
